name: Push trigger for swift-library

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**

jobs:
  build-swift:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build project
        run: xcodebuild -scheme pixelpass -destination 'generic/platform=iOS' build

      - name: Run tests
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep -m1 'iPhone' | awk -F '[()]' '{print $2}')
          echo "Using iOS Simulator ID: $DEVICE_ID"

          xcrun simctl boot "$DEVICE_ID" || echo "Simulator already booted"
          xcrun simctl list devices

          sleep 50

          xcrun xcodebuild test -scheme pixelpassTests -destination "platform=iOS Simulator,id=$DEVICE_ID" \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGN_IDENTITY="" \
           DEVELOPMENT_TEAM=""

      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: "${{ github.event_name != 'pull_request' && failure() }}"

  sonar_analysis:
    uses: tw-mosip/kattu/.github/workflows/swift-sonar-analysis.yml@injimob-2885
    if: "${{  github.event_name != 'pull_request' }}"
    with:
      SERVICE_LOCATION: "."
      TARGET_PLATFORM: "iOS"
      XC_SCHEME: "pixelpassTests"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
